# Generated by Django 5.0.3 on 2024-03-16 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 3, 22, 20, 647843, tzinfo=datetime.timezone.utc)),
        ),
    ]
