# Generated by Django 5.0.3 on 2024-03-16 08:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_itemcategory_itemsubcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSubcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 8, 57, 23, 133150, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RenameModel(
            old_name='ItemSubcategory',
            new_name='ItemCategories',
        ),
        migrations.AddField(
            model_name='itemsubcategories',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wardrobe.itemcategories'),
        ),
    ]
