# Generated by Django 5.0.3 on 2024-03-16 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_itemsubcategories_delete_itemcategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCategories',
            new_name='ItemCategory',
        ),
        migrations.RenameModel(
            old_name='ItemSubcategories',
            new_name='ItemSubcategory',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 8, 58, 36, 635742, tzinfo=datetime.timezone.utc)),
        ),
    ]
