# Generated by Django 5.0.3 on 2024-03-16 09:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0007_bodyshape_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 9, 22, 45, 10131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(max_length=500)),
                ('profilepic', models.ImageField(default='profpic/no_img.jpg', upload_to='profpic/')),
                ('birthdate', models.DateField()),
                ('height', models.IntegerField(max_length=3)),
                ('weight', models.IntegerField(max_length=3)),
                ('body_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.bodyshape')),
                ('pref_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.itemcolor')),
                ('pref_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.itemstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.useraccount')),
            ],
        ),
    ]
