# Generated by Django 5.0.3 on 2024-03-17 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0008_alter_useraccount_date_joined_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 9, 24, 59, 623924, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pref_color',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pref_style',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(default='profpic/default_userpic.png', upload_to='profpic/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_color',
            field=models.ManyToManyField(blank=True, to='wardrobe.itemcolor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_style',
            field=models.ManyToManyField(blank=True, to='wardrobe.itemstyle'),
        ),
    ]
