# Generated by Django 5.0.4 on 2024-04-13 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0009_alter_useraccount_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=50, null=True)),
                ('body_shape', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('style', models.CharField(max_length=100, null=True)),
                ('original_image', models.ImageField(null=True, upload_to='media/fashion_data/')),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 5, 40, 29, 601576, tzinfo=datetime.timezone.utc)),
        ),
    ]
