# Generated by Django 5.0.4 on 2024-04-13 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0010_fashionitem_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionitem',
            name='gendered',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 12, 8, 37, 309501, tzinfo=datetime.timezone.utc)),
        ),
    ]
