# Generated by Django 5.0.4 on 2024-04-15 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0012_userprofile_pref_genderedstyle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 0, 21, 10, 843728, tzinfo=datetime.timezone.utc)),
        ),
    ]
