# Generated by Django 5.0.4 on 2024-04-15 00:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0013_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionitem',
            name='user_save',
            field=models.ManyToManyField(blank=True, to='wardrobe.useraccount'),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='original_image',
            field=models.ImageField(null=True, upload_to='fashion_data/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 0, 38, 16, 100126, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=50, null=True)),
                ('body_shape', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('style', models.CharField(max_length=100, null=True)),
                ('gendered', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='user_items/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.useraccount')),
            ],
        ),
    ]
