# Generated by Django 5.0.4 on 2024-04-15 00:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0014_fashionitem_user_save_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 0, 47, 44, 450392, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='body_shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.bodyshape'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.itemcategory'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.itemcolor'),
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='style',
        ),
        migrations.AlterField(
            model_name='useritem',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.itemsubcategory'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='style',
            field=models.ManyToManyField(blank=True, to='wardrobe.itemstyle'),
        ),
    ]
