# Generated by Django 5.0.4 on 2024-04-17 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0016_remove_useritem_body_shape_remove_useritem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 9, 58, 50, 892241, tzinfo=datetime.timezone.utc)),
        ),
    ]
