# Generated by Django 5.0.4 on 2024-04-21 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0019_rename_useroutfits_useroutfit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroutfit',
            old_name='c_bottom',
            new_name='bottom',
        ),
        migrations.RenameField(
            model_name='useroutfit',
            old_name='c_footwear',
            new_name='footwear',
        ),
        migrations.RenameField(
            model_name='useroutfit',
            old_name='c_outerwear',
            new_name='outerwear',
        ),
        migrations.RenameField(
            model_name='useroutfit',
            old_name='c_top',
            new_name='top',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 15, 45, 21, 354643, tzinfo=datetime.timezone.utc)),
        ),
    ]
