# Generated by Django 5.0.4 on 2024-04-21 16:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0020_rename_c_bottom_useroutfit_bottom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 16, 2, 28, 4843, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useroutfit',
            name='outerwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outerwear_outfits', to='wardrobe.useritem'),
        ),
    ]
