# Generated by Django 5.0.4 on 2024-05-06 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0021_alter_useraccount_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 2, 50, 49, 807332, tzinfo=datetime.timezone.utc)),
        ),
    ]
