# Generated by Django 5.0.4 on 2024-05-06 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0022_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 3, 12, 14, 814352, tzinfo=datetime.timezone.utc)),
        ),
    ]
