# Generated by Django 5.0.4 on 2024-05-09 02:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0023_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 2, 51, 5, 291587, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Outfit_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.useraccount')),
                ('user_outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.useroutfit')),
            ],
        ),
    ]
