# Generated by Django 5.0.4 on 2024-05-12 13:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0026_remove_outfitplan_user_outfit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionitem',
            name='user_save',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 13, 52, 3, 141700, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='user_post/')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('user_outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.useroutfit')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.useraccount')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.userpost')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='user_post/')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.useraccount')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.userpost')),
            ],
        ),
        migrations.CreateModel(
            name='UserReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='user_post/')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.useraccount')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.usercomment')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.fashionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.useraccount')),
            ],
        ),
    ]
