# Generated by Django 5.0.4 on 2024-05-23 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0029_alter_useraccount_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroutfit',
            name='accessories',
            field=models.ManyToManyField(blank=True, to='wardrobe.useritem'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 6, 34, 16, 672762, tzinfo=datetime.timezone.utc)),
        ),
    ]
