# Generated by Django 5.0.4 on 2024-05-26 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0032_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 9, 44, 53, 379201, tzinfo=datetime.timezone.utc)),
        ),
    ]
