# Generated by Django 5.0.4 on 2024-05-26 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0033_useraccount_code_useraccount_isverified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 9, 52, 33, 276641, tzinfo=datetime.timezone.utc)),
        ),
    ]
