# Generated by Django 5.0.4 on 2024-05-26 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0034_alter_useraccount_code_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcolor',
            name='name',
            field=models.CharField(default=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='code',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 9, 53, 56, 335887, tzinfo=datetime.timezone.utc)),
        ),
    ]
